modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "edenring"
version = "${version}"
displayName = "Eden Ring Reforked (Multiplatorm Forge)"
authors = "BetterX Fork Dev Team"
description = '''
Sci-Fi dimension mod with some unique things!
'''
#logoFile = ""

[[dependencies.edenring]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edenring]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edenring]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
